# Generated by Django 5.0.1 on 2024-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
