# Generated by Django 5.0.1 on 2024-02-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('password', models.CharField(max_length=20)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default='False')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='email', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
