# Generated by Django 5.0.1 on 2024-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userprofile_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
