# Generated by Django 5.0.1 on 2024-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_userprofile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='Verified',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=100),
        ),
    ]
