# Generated by Django 5.0.1 on 2024-02-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_userprofile_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verified',
            new_name='Verified',
        ),
    ]
