# Generated by Django 5.0.1 on 2024-02-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_verified_userprofile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
    ]
