# Generated by Django 5.0.1 on 2024-02-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_userprofile_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='method',
            new_name='registration_method',
        ),
    ]
