# Generated by Django 5.0.1 on 2024-02-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_is_verified_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staff',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
