# Generated by Django 5.0.1 on 2024-02-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_rename_is_verified_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(),
        ),
    ]
