# Generated by Django 5.0.1 on 2024-02-05 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_userprofile_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.MaxLengthValidator(limit_value=6)]),
        ),
    ]
