# Generated by Django 5.0.1 on 2024-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
