# Generated by Django 5.0.1 on 2024-02-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_remove_customuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
