# Generated by Django 5.0.1 on 2024-02-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
