# Generated by Django 5.0.1 on 2024-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_rename_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
