# Generated by Django 5.0.1 on 2024-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleGroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroupworkout',
            name='musclegroup',
            field=models.CharField(default='n', max_length=100, verbose_name='MuscleGroup Name'),
        ),
    ]
