# Generated by Django 5.0.1 on 2024-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleGroups', '0002_musclegroupworkout_musclegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musclegroupworkout',
            options={'ordering': ['msw_name'], 'verbose_name': 'MuscleGroup Workout'},
        ),
        migrations.RemoveField(
            model_name='musclegroupworkout',
            name='name',
        ),
        migrations.AddField(
            model_name='musclegroupworkout',
            name='msw_name',
            field=models.CharField(default='f', max_length=100, verbose_name='MuscleGroupWorkout Name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='musclegroup_workout',
            field=models.CharField(default='n', max_length=100),
        ),
    ]
