# Generated by Django 5.0.1 on 2024-02-07 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscleGroups', '0003_alter_musclegroupworkout_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workouts_photos')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_images', to='muscleGroups.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='images',
            field=models.ManyToManyField(related_name='workouts', to='muscleGroups.workoutimage'),
        ),
    ]
