# Generated by Django 5.0.1 on 2024-02-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscleGroups', '0004_workoutimage_workout_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='images',
        ),
        migrations.DeleteModel(
            name='WorkoutImage',
        ),
    ]
